version: '3'

services:
  wms-api:
    build: .
    image: sourcecheck/wms-api
    container_name: sc-wms-api
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
    ports:
      - 1337:1337
    depends_on:
      - wms-redis
      - wms-database

  wms-database:
    image: mysql
    container_name: sc-wms-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql

  wms-redis:
    image: redis
    container_name: sc-wms-redis
    restart: unless-stopped
    ports:
      - 6379:6379
      
networks:
  default:
    external:
      name: webproxy
